# Generated by Django 3.1.7 on 2021-03-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210307_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Varients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='uoms',
            field=models.ManyToManyField(blank=True, null=True, to='store.UOM'),
        ),
        migrations.AddField(
            model_name='product',
            name='varients',
            field=models.ManyToManyField(blank=True, null=True, to='store.Varients'),
        ),
    ]
