# Generated by Django 3.1.7 on 2021-03-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210307_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uoms',
            field=models.ManyToManyField(blank=True, default='Please Enter UOM', null=True, to='store.UOM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='varients',
            field=models.ManyToManyField(blank=True, default='Please Select Varients', null=True, to='store.Varients'),
        ),
    ]
