# Generated by Django 3.1.7 on 2021-03-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210308_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uoms',
        ),
        migrations.RemoveField(
            model_name='product',
            name='varients',
        ),
        migrations.DeleteModel(
            name='UOM',
        ),
        migrations.DeleteModel(
            name='Varients',
        ),
    ]
