# Generated by Django 3.1.7 on 2021-03-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210309_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ums', to='store.product'),
        ),
    ]
