# Generated by Django 3.1.7 on 2021-03-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210312_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
