# Generated by Django 3.1.7 on 2021-03-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210307_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uom',
        ),
        migrations.DeleteModel(
            name='UOM',
        ),
    ]
